# scripts/core/event_bus.gd — владелец: 03 Technical Director / 05 Senior Godot Developer
# Глобальная шина сигналов (автозагрузка). Единственный канал межмодульной связи.
# ВАЖНО: без @warning_ignore_* — в 4.7.stable они не распознаются (ломали компиляцию).
extends Node

signal game_state_changed(new_state: int)
signal game_started()
signal game_over()
signal game_won()
signal district_stage_changed(district_id: StringName, stage: int)
signal district_restored(district_id: StringName, stage: int)
signal district_entered(district_id: StringName)
signal district_blackout(district_id: StringName)
signal power_grid_updated()
signal puzzle_solved(puzzle_id: StringName, district_id: StringName)
signal player_state_changed(state: int)
signal player_health_changed(ratio: float)
signal player_stamina_changed(ratio: float)
signal player_battery_changed(ratio: float)
signal player_interact_available(available: bool)
signal player_stealth_changed(stealth: bool)
signal flashlight_changed()
signal flashlight_state_changed(enabled: bool)
signal flashlight_depleted()
signal light_level_changed(level: float)
signal light_disrupted()
signal item_picked_up(item_id: StringName)
signal inventory_changed()
signal inventory_weight_changed(ratio: float)
signal inventory_notice(text: String)
signal inventory_toggle_requested()
signal item_consumed(item_id: StringName, effect: StringName, value: float)
signal examine_text(text: String)
signal secret_found(secret_id: StringName)
signal coins_changed(new_amount: int)
signal purchase_failed(reason: String)
signal purchase_success(item_id: StringName)
signal shop_toggle_requested()
signal skin_unlocked(skin_id: StringName)
signal achievement_unlocked(achievement_id: StringName)
signal weather_changed(weather: int, name: String, fog: float, rain: float)
signal hud_visibility_changed(visible: bool)
signal photo_mode_toggled(active: bool)
signal settings_changed(bus: String, value: float)
signal document_unlocked(doc_id: StringName)
signal monster_spotted(monster_id: StringName)
signal enemy_killed(monster_id: StringName)
signal enemy_attack(damage: int)
signal player_died
signal boss_defeated
signal level_completed(level: int)
signal xp_gained(amount: int)
signal wave_completed(wave: int)
signal encyclopedia_unlocked(monster_id: StringName)
signal noise_emitted(global_pos: Vector2, radius: float)
signal ui_screen_opened(screen_id: StringName)
signal ui_screen_closed(screen_id: StringName)
signal ammo_changed(current: int, max_ammo: int)
signal enemy_died(pos: Vector3)
signal enemy_encountered(type: StringName)
signal enemy_hp_updated(ratio: float)
signal enemy_spawned(enemy: Node3D)
signal interaction_done(target_id: StringName)
signal player_damaged(amount: int)
signal zone_reached(zone_id: StringName)
signal player_detected(monster_id: StringName)
signal final_night_started()
signal health_changed(amount: float)
signal purchase_done(item_id: StringName, success: bool)
signal quest_completed(quest_id: StringName)
signal radar_marker_added(marker: Vector3)

## Эти три сигнала уже эмитились/слушались в коде, но объявлены не были:
## player_3d.gd эмитил player_hiding_changed «в пустоту», а tutorial_system.gd
## падал на connect() к puzzle_started и обрывал регистрацию остальных
## подписок — обучение переставало реагировать на события после этой строки.
signal player_hiding_changed(hiding: bool)
signal puzzle_started(puzzle_id: StringName)
signal streetlight_activated(light_id: StringName)

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
