#!/usr/bin/env python3
"""Finishing pipeline for generated in-game art.

Every plate in docs/ASSET_PROMPT_PACK.md is generated by an image model and
then finished here. The grade is what turns 73 individually generated pictures
into one coherent set, and it exists because the image model cannot be trusted
with the palette canon on its own.

What it does, in order:

  1. crop   - trims to the row's stated aspect ratio (centre-weighted, so a
              plate is never stretched)
  2. resize - LANCZOS to the row's stated pixel size
  3. sharpen- a light unsharp mask, applied only when the step was an upscale
              (the generator caps at 1376x768, so a 1920x1080 plate is a 1.4x
              upscale that otherwise reads soft)
  4. grade  - the house grade (see below)
  5. match  - optional grading toward measured luminance / warmth targets

The house grade enforces two palette rules from PRODUCTION_BIBLE.md §2 and
ASSET_PROMPT_PACK.md §3:

  * pure #000000 and #ffffff are banned. Black is lifted to the bg-deep floor
    (#0c1016, ~12/255) and highlights get a soft tanh rolloff instead of
    clipping, so a plate keeps a foot in both ends of the range.
  * colours stay muted and desaturated, so chroma is pulled toward luma.

Step 5 exists for plates whose order in play is load-bearing - currently the
five endings, which GDD §12.4 requires to run coldest to warmest. Exposure is
applied as a gain ABOVE the floor, not to the whole range: scaling the whole
range dragged the darkest plate back under the floor and re-created the pure
black the canon bans (ending_dark measured 23.6% of pixels under L=8 before
this was fixed).

Usage:

    python3 tools/art_finish.py --plan plan.json      # finish a batch
    python3 tools/art_finish.py --report FILE.png ... # measure finished art

plan.json is a list of rows:
    [{"src": "art_drop/menu_hero.png",
      "dst": "assets/textures/screens_v2/menu_hero.png",
      "size": [1920, 1080],
      "target_lum": 28.0,     # optional
      "target_rb": -20.0}]    # optional

Needs Pillow and numpy. Lives in tools/, which export_presets.cfg excludes
from the shipped build - it is a build-time tool, not game code.
"""

import argparse
import json
import sys

import numpy as np
from PIL import Image, ImageFilter

LUMA = np.array([0.2126, 0.7152, 0.0722])

# 0.047 * 255 ~= 12, the bg-deep #0c1016 floor. Nothing in this game is pure black.
BLACK_FLOOR = 0.047
# Highlights start rolling off here instead of clipping to pure white.
HIGHLIGHT_KNEE = 0.82
# Pull chroma toward luma for the muted, desaturated house look.
DESAT = 0.10


def load(path):
    return np.asarray(Image.open(path).convert("RGB"), dtype=np.float64) / 255.0


def crop_to_ar(a, target_ar):
    """Trim to the target aspect ratio. Centre-weighted: never stretch."""
    h, w, _ = a.shape
    cur = w / h
    if abs(cur - target_ar) < 0.005:
        return a
    if cur > target_ar:                                   # too wide: trim sides
        nw = int(round(h * target_ar))
        x0 = (w - nw) // 2
        return a[:, x0:x0 + nw]
    nh = int(round(w / target_ar))                        # too tall: trim top/bottom
    y0 = (h - nh) // 2
    return a[y0:y0 + nh, :]


def resize(a, width, height):
    im = Image.fromarray((np.clip(a, 0, 1) * 255).astype(np.uint8))
    factor = width / im.size[0]
    im = im.resize((width, height), Image.LANCZOS)
    if factor > 1.05:
        im = im.filter(ImageFilter.UnsharpMask(radius=1.2, percent=55, threshold=3))
    return np.asarray(im, dtype=np.float64) / 255.0


def house_grade(a, black=BLACK_FLOOR, white=0.965, desat=DESAT):
    a = black + a * (white - black)
    luma = a @ LUMA
    a = a * (1.0 - desat) + luma[..., None] * desat
    return np.clip(a, 0, 1)


def soft_highlight(a, knee=HIGHLIGHT_KNEE):
    out = a.copy()
    m = a > knee
    out[m] = knee + (1.0 - knee) * np.tanh((a[m] - knee) / (1.0 - knee))
    return out


def match_targets(a, target_lum=None, target_rb=None, floor=BLACK_FLOOR, iters=12):
    a = a * 255.0
    fl = floor * 255.0
    for _ in range(iters):
        if target_lum is not None:
            cur = float((a @ LUMA).mean())
            span = cur - fl
            if span > 0.5 and target_lum > fl:
                a = fl + (a - fl) * ((target_lum - fl) / span)
        if target_rb is not None:
            cur_rb = float((a[..., 0] - a[..., 2]).mean())
            d = (target_rb - cur_rb) / 2.0
            a[..., 0] = a[..., 0] + d
            a[..., 2] = a[..., 2] - d
        a = np.clip(a, fl, 255)
    return a / 255.0


def finish(src, dst, size, black=BLACK_FLOOR, desat=DESAT,
           target_lum=None, target_rb=None):
    a = load(src)
    a = crop_to_ar(a, size[0] / size[1])
    a = resize(a, size[0], size[1])
    a = house_grade(a, black=black, desat=desat)
    a = soft_highlight(a)
    if target_lum is not None or target_rb is not None:
        a = match_targets(a, target_lum, target_rb)
        a = soft_highlight(a)
    a = np.clip(a, 0, 1)
    Image.fromarray((a * 255).astype(np.uint8)).save(dst, optimize=True)
    return a


def measure(a):
    lum = (a @ LUMA) * 255.0
    rb = (a[..., 0] - a[..., 2]) * 255.0
    return {
        "mean_lum": round(float(lum.mean()), 1),
        "mean_rb": round(float(rb.mean()), 1),
        "blown_pct": round(float((lum > 250).mean() * 100), 2),
        "pure_black_pct": round(float((lum < 8).mean() * 100), 1),
    }


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--plan", help="JSON batch plan (see module docstring)")
    p.add_argument("--report", nargs="+", help="measure finished files, print stats")
    args = p.parse_args()

    if args.report:
        print(f"{'file':44} {'meanL':>6} {'R-B':>7} {'blown%':>7} {'black%':>7}")
        for path in args.report:
            m = measure(load(path))
            name = path.split("/")[-1]
            print(f"{name:44} {m['mean_lum']:6.1f} {m['mean_rb']:7.1f} "
                  f"{m['blown_pct']:7.2f} {m['pure_black_pct']:7.1f}")
        return 0

    if not args.plan:
        p.error("give --plan or --report")

    with open(args.plan) as fh:
        rows = json.load(fh)
    for row in rows:
        a = finish(row["src"], row["dst"], tuple(row["size"]),
                   target_lum=row.get("target_lum"), target_rb=row.get("target_rb"))
        m = measure(a)
        print(f"{row['dst'].split('/')[-1]:36} meanL={m['mean_lum']:5.1f} "
              f"R-B={m['mean_rb']:6.1f} blown={m['blown_pct']:5.2f}% "
              f"black={m['pure_black_pct']:4.1f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
