# -*- coding: utf-8 -*-
"""Writes the rc16 section of docs/PROOFS.md (AF1) from docs/artifacts/rc16/closures.json.

usage: python tools/qa_sim/gen_proofs16.py [--demo]
A closure is {"id", "claim", "cmd", "proof", "quotes": [needle, ...], "frames": [path, ...], "commit"}. `proof` names a raw log written by
tools/qa_sim/proof_run (docs/artifacts/rc16/proofs/<proof>.out, untrimmed, with its exit code); every quote is the FIRST line of that log that
contains the needle, copied verbatim, so a quote cannot drift from the log; a needle that no line contains stops the generator. A frame is
cited by path with the capture time written in its name. The section sits between two markers in docs/PROOFS.md and is rewritten in place.
"""
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PROOFS = ROOT / "docs" / "PROOFS.md"
CLOSURES = ROOT / "docs" / "artifacts" / "rc16" / "closures.json"
LOGS = ROOT / "docs" / "artifacts" / "rc16" / "proofs"
BEGIN, END = "<!-- rc16:begin -->", "<!-- rc16:end -->"
EXIT = re.compile(r"^# EXIT=(\d+)$", re.M)
STAMP = re.compile(r"_(\d{8}T\d{6}Z)\.png$")


def cell(text):
    return text.replace("|", "\\|").replace("\n", " ")


def row(c):
    log = LOGS / (c["proof"] + ".out")
    data = log.read_bytes()
    text = data.decode("utf-8", errors="replace")
    m = EXIT.search(text)
    code = m.group(1) if m else "?"
    lines = text.splitlines()
    quotes = []
    for needle in c.get("quotes", []):
        hit = next((ln for ln in lines if needle in ln), None)
        if hit is None:
            raise SystemExit("evidence line not found: %s / %s" % (c["proof"], needle))
        quotes.append("`%s`" % cell(hit.strip()))
    frames = []
    for f in c.get("frames", []):
        if not (ROOT / f).exists():
            raise SystemExit("frame not found: " + f)
        s = STAMP.search(f)
        frames.append("`%s` (captured %s)" % (f, s.group(1) if s else "?"))
    evidence = " ; ".join(quotes + frames)
    return "| %s | %s | `%s` | %s | `docs/artifacts/rc16/proofs/%s.out` sha256 `%s` | %s | %s |" % (
        c["id"], cell(c["claim"]), cell(c["cmd"]), code, c["proof"], hashlib.sha256(data).hexdigest()[:16], evidence, c["commit"])


def build(closures):
    out = [BEGIN, "", "# PROOFS (rc16 closeout)", "",
           "Every closure is one row: ID | claim | command | exit code | raw log (untrimmed, with its exit code; sha256 of the file) | quoted lines "
           "(each the first line of the log that contains the needle, verbatim) or frame paths with their capture time | commit. The logs are written by "
           "`tools/qa_sim/proof_run`; this section is generated by `tools/qa_sim/gen_proofs16.py` from `docs/artifacts/rc16/closures.json`, so a quote cannot drift "
           "from its log. A claim without a row here is FAKE and is reverted with a CORRECTION_LOG row.", "",
           "| ID | claim | command | exit | raw log | evidence | commit |", "|---|---|---|---|---|---|---|"]
    out += [row(c) for c in closures]
    out += ["", "## Launch ledger (rc16)", "", "`docs/artifacts/rc16/launch_ledger.tsv`, one row per top-level Godot launch command written by `proof_run --launch`:", ""]
    ledger = ROOT / "docs" / "artifacts" / "rc16" / "launch_ledger.tsv"
    if ledger.exists():
        lines = ledger.read_text(encoding="utf-8").splitlines()
        out += ["| " + " | ".join(ln.split("\t")) + " |" for ln in lines[:1]] + ["|---|---|---|---|---|---|"]
        out += ["| " + " | ".join(ln.split("\t")) + " |" for ln in lines[1:]]
    out += ["", END]
    return "\n".join(out) + "\n"


def demo():
    assert cell("a|b\nc") == "a\\|b c"
    assert STAMP.search("x_after_a1b2c3d_20261003T014512Z.png").group(1) == "20261003T014512Z"
    assert EXIT.search("body\n# EXIT=0\n").group(1) == "0"
    print("gen_proofs16 demo OK")


def main():
    if "--demo" in sys.argv:
        demo()
        return 0
    closures = json.loads(CLOSURES.read_text(encoding="utf-8"))
    section = build(closures)
    text = PROOFS.read_text(encoding="utf-8")
    crlf = "\r\n" in text
    text = text.replace("\r\n", "\n")
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        tail = rest.split(END, 1)[1] if END in rest else ""
        text = head.rstrip("\n") + "\n\n" + section + tail.lstrip("\n")
    else:
        text = text.rstrip("\n") + "\n\n" + section
    PROOFS.write_bytes((text.replace("\n", "\r\n") if crlf else text).encode("utf-8"))
    print("PROOFS.md rc16 section: %d closures" % len(closures))
    return 0


if __name__ == "__main__":
    sys.exit(main())
